### ISSUE TITLE
draw_box draw only one box from layout

### ISSUE THREAD

**Issue by Moo1234567** [Layout-Parser/layout-parser#131]
**Describe the bug**
I just installed everything according to the installation guide and launched your jupyter notebook from here [Deep Layout Parsing Example](https://github.com/Layout-Parser/layout-parser/blob/main/examples/Deep%20Layout%20Parsing.ipynb). After first draw_box it's show only one box, but in print(layout) i see all boxes. Same with second draw_box from your guide. not sure what i'm doing wrong.

**To Reproduce**
1.  installation guide + detectron2 install also from your guide
2. Run jupyter notebook

**Environment**
```
1. MacOS
2. VS Code
3. Here some stuff from pip:
torch==1.11.0
torchvision==0.12.0
Pillow==9.1.0
opencv-python==4.5.5.64
layoutparser==0.3.3
```
**Error traceback**
No errors, just behaviour not same like in guide or other guides

**Screenshots**
attached

![output1](https://user-images.githubusercontent.com/60774756/161797269-7ca71385-5c0d-4aea-8f8c-aadf3801b233.png)
![output2](https://user-images.githubusercontent.com/60774756/161797305-74b504a4-14e9-40be-b4dd-0abc6fc2484d.png)

**Comment by Moo1234567** [comment]
downgraded to 0.3.2. all working like a charm. so it's definitely bug in new 0.3.3 release

**Comment by lolipopshock** [comment]
Thank you @Moo1234567 ! It should be fixed in #132 and I'll release it shortly.

**Comment by Jim-Salmons** [comment]
Came here to report the same issue but will look for the update and test. 

Otherwise, I am now on an M1 iMac and the install via homebrew, miniconda and pip using the `osx-arm64` architecture went super smooth. The only issue I had was with a pip install of `grpcio` which used an `osx-64` module. All I had to do was uninstall via pip and install an `osx-arm64` version via conda. Compared to my Windows 10 install many months ago, this was a breeze. Looking forward to the update and getting back to work on a wxPython-based layout result tweaker tool for my MAGAZINEgts ground truth storage format development I back-burnered due to my spinal cord injury. (GitHub Copilot rocks for disabled developers!)

BTW, I am not even sure if the MacOS `arm64` issue on `grpcio` is related to the `layoutparser` fresh install as I was also including `wxpython`, `pypubsub`, and `nuitka` in the environment... all running happy now in `arm64`. Great work on 0.3.3 @lolipopshock & contributors!

**Comment by Jim-Salmons** [comment]
Excellent! :-) Just updated to 0.3.4 and confirm the fix. TY
